### ISSUE TITLE
Poly-kinded tuple constraints?

### ISSUE THREAD

**Issue by sheaf** [RyanGlScott/constraint-tuples#1]
I apologise for the drive-by comment, but I'm wondering whether it would be possible to include poly-kinded tuple constraints.

As far as I understand, this library only handles tuples of things with type `Constraint`. However I'd also like to be able to take products of partially applied type classes, and so would like tuples with types:

```haskell
type Tuple21 :: ( k1 -> Constraint ) -> ( k1 -> Constraint ) -> ( k1 -> Constraint )
type Tuple22 :: ( k1 -> k2 -> Constraint ) -> ( k1 -> k2 -> Constraint ) -> ( k1 -> k2 -> Constraint )
type Tuple31 :: ( k1 -> Constraint ) -> ( k1 -> Constraint ) -> ( k1 -> Constraint ) -> ( k1 -> Constraint )
...
```

Is there a way to include this functionality without having to tediously write out all combinations by hand?

**Comment by RyanGlScott** [comment]
Per the [`README`](https://github.com/RyanGlScott/constraint-tuples/blob/1ccbf0c097335ca0e6b55dca1833b298a7cbfb09/README.md#constraint-tuples), the scope of this library is limited to emulating GHC's constraint tuples, which have special syntax when compared to other type classes. As such, I would consider including other classes (such as the ones you propose) out of scope, as these are different classes altogether.

That being said, I imagine that you could generate such classes by adapting [this generator script](https://github.com/RyanGlScott/constraint-tuples/blob/1ccbf0c097335ca0e6b55dca1833b298a7cbfb09/generator-script/exe/GeneratorScript.hs), which is what I use to generate the code in this library.
